export class MoonbaseCanvasRenderer {
  constructor(canvas, engine) { this.canvas = canvas; this.ctx = canvas.getContext('2d'); this.engine = engine; this.particles = []; this.glow = 0; this.resize(); window.addEventListener('resize', () => this.resize()); }
  resize() { const r = this.canvas.parentElement.getBoundingClientRect(); const dpr = devicePixelRatio || 1; this.width = r.width; this.height = Math.max(420, Math.min(580, innerHeight * .52)); this.canvas.width = this.width * dpr; this.canvas.height = this.height * dpr; this.canvas.style.width = `${this.width}px`; this.canvas.style.height = `${this.height}px`; this.ctx.setTransform(dpr, 0, 0, dpr, 0, 0); }
  notifyDimensionChange() { this.glow = 1; }
  triggerCelebration() { for (let i = 0; i < 60; i++) this.particles.push({ x: this.width / 2, y: this.height / 2, vx: (Math.random() - .5) * 8, vy: -Math.random() * 7, a: 1 }); }
  render(time) { const c = this.ctx, w = this.width, h = this.height, calc = this.engine.getCalculations(); c.fillStyle = '#070D18'; c.fillRect(0, 0, w, h); this.grid(c, w, h); this.plot(c, w, h, calc, time / 1000); this.particles.forEach(p => { p.x += p.vx; p.y += p.vy; p.vy += .15; p.a -= .02; c.fillStyle = `rgba(79,209,197,${p.a})`; c.fillRect(p.x, p.y, 4, 4); }); this.particles = this.particles.filter(p => p.a > 0); }
  grid(c, w, h) { c.strokeStyle = 'rgba(90,120,150,.18)'; c.lineWidth = 1; for (let x = 40; x < w - 20; x += 32) { c.beginPath(); c.moveTo(x, 20); c.lineTo(x, h - 35); c.stroke(); } for (let y = 25; y < h - 35; y += 32) { c.beginPath(); c.moveTo(25, y); c.lineTo(w - 20, y); c.stroke(); } }
  plot(c, w, h, calc, t) { const left = 58, right = w - 34, top = 42, bottom = h - 55, midY = (top + bottom) / 2, scaleX = (right - left) / 12, scaleY = 48; c.strokeStyle = '#6B7C93'; c.beginPath(); c.moveTo(left, midY); c.lineTo(right, midY); c.moveTo((left + right) / 2, top); c.lineTo((left + right) / 2, bottom); c.stroke(); c.fillStyle = '#8A9BB4'; c.font = '11px JetBrains Mono'; c.fillText(calc.mission.type === 'fourier' ? 'time → frequency' : calc.mission.type === 'electrostatics' || calc.mission.type === 'gauss' ? 'field geometry' : 'state space', left, 20);
    c.strokeStyle = '#4FD1C5'; c.lineWidth = 2; c.beginPath(); for (let i = 0; i <= 180; i++) { const u = -6 + i / 15; let y; if (calc.mission.type === 'derivative') y = u ** 3 / 12 - u / 2; else if (calc.mission.type === 'integral') y = Math.sin(u); else if (calc.mission.type === 'fourier') y = Math.sin(1.5 * u) + .6 * Math.sin(Math.max(.2, Math.abs(this.engine.length)) * u); else y = calc.mission.type === 'gauss' ? 1 / Math.max(.5, Math.abs(u)) ** 2 : 1 / Math.max(.5, Math.abs(u)); const px = left + (u + 6) * scaleX; const py = midY - y * scaleY; i ? c.lineTo(px, py) : c.moveTo(px, py); } c.stroke();
    const px = left + (Math.max(-6, Math.min(6, this.engine.width)) + 6) * scaleX; let val = calc.mission.type === 'derivative' ? this.engine.width ** 3 / 12 - this.engine.width / 2 : calc.mission.type === 'integral' ? Math.sin(this.engine.width) : calc.mission.type === 'fourier' ? Math.sin(1.5 * this.engine.width) + .6 * Math.sin(Math.max(.2, Math.abs(this.engine.length)) * this.engine.width) : calc.mission.type === 'gauss' ? 1 / Math.max(.5, Math.abs(this.engine.width)) ** 2 : 1 / Math.max(.5, Math.abs(this.engine.width)); const py = midY - val * scaleY; c.fillStyle = '#F6C76D'; c.beginPath(); c.arc(px, py, 8 + Math.sin(t * 4) * 2, 0, Math.PI * 2); c.fill(); c.fillStyle = '#F6C76D'; c.fillText(`state (${this.engine.width.toFixed(1)}, ${this.engine.length.toFixed(1)})`, Math.min(px + 12, right - 130), Math.max(top + 14, py - 12));
    if (calc.mission.type === 'derivative') { c.strokeStyle = '#E8A33D'; c.beginPath(); const slope = 3 * this.engine.width ** 2 - 3; c.moveTo(px - 70, py + slope * 4); c.lineTo(px + 70, py - slope * 4); c.stroke(); }
  }
}
