(() => {
  const canvas=document.querySelector('#pond'),ctx=canvas.getContext('2d'),W=canvas.width,H=canvas.height;
  const $=id=>document.getElementById(id), rand=(a,b)=>a+Math.random()*(b-a), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const names=['Mabel','Rupert','Pearl','Gus','Clover','Biscuit'], colors=['#f7e9bc','#f1cf77','#f7f3db','#d8b05e','#f6d996','#e9e3c7'];
  let ducks,food,lilies,rain,events,hover=null,ticks=0;
  function log(text){events.unshift({text,t:ticks});events=events.slice(0,7);renderEvents()}
  function reset(){ticks=0;food=[];lilies=[{x:W*.28,y:H*.67,r:31},{x:W*.72,y:H*.27,r:25},{x:W*.63,y:H*.75,r:20}];rain=0;events=[];ducks=names.map((name,i)=>({name,color:colors[i],x:rand(100,W-100),y:rand(100,H-100),vx:0,vy:0,hunger:rand(.15,.55),energy:1,territory:rand(0,Math.PI*2),friends:{},grudges:{},state:'exploring',target:null})); log('The pond wakes. Everyone is pretending not to look at everyone else.');}
  function affinity(a,b){return (a.friends[b.name]||0)-(a.grudges[b.name]||0)}
  function pickTarget(d){let nearest=null,best=Infinity;food.forEach(f=>{let q=Math.hypot(f.x-d.x,f.y-d.y);if(q<best){best=q;nearest=f}});if(nearest&&best<260){d.target=nearest;d.state='foraging';return}let candidates=ducks.filter(x=>x!==d);let pal=candidates.sort((a,b)=>affinity(d,b)-affinity(d,a))[0];if(pal&&affinity(d,pal)>.38&&Math.random()<.02){d.target=pal;d.state='following';return}d.target={x:W/2+Math.cos(d.territory+rand(-.9,.9))*rand(70,230),y:H/2+Math.sin(d.territory+rand(-.9,.9))*rand(50,160)};d.state='patrolling'}
  function step(){ticks++; rain=Math.max(0,rain-.006);ducks.forEach(d=>{d.hunger=clamp(d.hunger+.00045,0,1);d.energy=clamp(d.energy+(rain?.00025:-.0001),.25,1);if(!d.target||Math.random()<.012)pickTarget(d);let t=d.target,dx=t.x-d.x,dy=t.y-d.y,dist=Math.hypot(dx,dy)||1;let speed=d.state==='foraging'?1.2:.72;d.vx=d.vx*.88+dx/dist*speed*.12;d.vy=d.vy*.88+dy/dist*speed*.12;d.x=clamp(d.x+d.vx,34,W-34);d.y=clamp(d.y+d.vy,34,H-34);if(d.state==='foraging'&&dist<14){d.hunger=clamp(d.hunger-.38,0,1);food=food.filter(f=>f!==t);log(`${d.name} found the breadcrumbs. Courtesy ended immediately.`);d.target=null} });
    for(let i=0;i<ducks.length;i++)for(let j=i+1;j<ducks.length;j++){let a=ducks[i],b=ducks[j],dist=Math.hypot(a.x-b.x,a.y-b.y);if(dist<44){let friendly=Math.random()<.56;if(friendly){a.friends[b.name]=clamp((a.friends[b.name]||0)+.012,0,1);b.friends[a.name]=clamp((b.friends[a.name]||0)+.012,0,1)}else if(Math.random()<.12){a.grudges[b.name]=clamp((a.grudges[b.name]||0)+.025,0,1); if(Math.random()<.02)log(`${a.name} displaced ${b.name} and has not forgiven the incident.`)} }} if(ticks%90===0&&rain>.1)log('Rain softened the pond. Old grievances seem temporarily less important.');renderReadout()}
  function water(){let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#397f87');g.addColorStop(1,'#174a59');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=0;i<32;i++){ctx.strokeStyle=`rgba(220,255,235,${.04+Math.sin(ticks*.03+i)*.02})`;ctx.beginPath();let y=(i*43+ticks*.22)%H;ctx.moveTo(0,y);ctx.bezierCurveTo(W*.3,y-12,W*.7,y+12,W,y);ctx.stroke()}if(rain){ctx.strokeStyle='rgba(222,245,255,.5)';for(let i=0;i<80;i++){let x=(i*73+ticks*4)%W,y=(i*113+ticks*7)%H;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-5,y+13);ctx.stroke()}}}
  function draw(){water();lilies.forEach(l=>{ctx.fillStyle='#4f7d44';ctx.beginPath();ctx.arc(l.x,l.y,l.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#d8e8ba';ctx.beginPath();ctx.arc(l.x+l.r*.14,l.y-l.r*.13,l.r*.22,0,Math.PI*2);ctx.fill()});food.forEach(f=>{ctx.fillStyle='#f6d176';ctx.beginPath();ctx.arc(f.x,f.y,5,0,7);ctx.fill()});ducks.forEach(d=>{ctx.save();ctx.translate(d.x,d.y);ctx.rotate(Math.atan2(d.vy,d.vx)||0);ctx.fillStyle='rgba(0,25,32,.18)';ctx.beginPath();ctx.ellipse(0,10,23,7,0,0,7);ctx.fill();ctx.fillStyle=d.color;ctx.beginPath();ctx.ellipse(0,0,19,12,0,0,7);ctx.fill();ctx.beginPath();ctx.arc(14,-7,9,0,7);ctx.fill();ctx.fillStyle='#e08c3e';ctx.beginPath();ctx.moveTo(22,-7);ctx.lineTo(31,-3);ctx.lineTo(22,0);ctx.fill();ctx.fillStyle='#192c2e';ctx.beginPath();ctx.arc(17,-10,1.8,0,7);ctx.fill();ctx.restore();if(hover===d){ctx.fillStyle='#fff2c6';ctx.font='12px DM Mono';ctx.fillText(d.name,d.x-20,d.y-25)}});requestAnimationFrame(draw)}
  function renderEvents(){$('events').innerHTML=events.map(e=>`<li><time>pond minute ${Math.floor(e.t/60)+1}</time>${e.text}</li>`).join('')}
  function renderReadout(){let pairs=0,best=null;ducks.forEach(a=>ducks.forEach(b=>{if(a!==b&&affinity(a,b)>.45){pairs++;best=best||`${a.name} & ${b.name}`}}));let contested=ducks.filter(d=>Object.values(d.grudges).some(v=>v>.35)).length;$('friends').textContent=best?`${best}${pairs>2?' + others':''}`:'forming slowly';$('territory').textContent=contested?`${contested} ducks feeling possessive`:'mostly shared';let hungry=ducks.filter(d=>d.hunger>.75).length;$('mood').textContent=rain>.1?'rainy détente':hungry>3?'bread-related tension':contested?'a little territorial':'unreasonably peaceful'}
  canvas.addEventListener('click',e=>{let r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height;for(let i=0;i<8;i++)food.push({x:x+rand(-24,24),y:y+rand(-18,18)});log('Breadcrumbs hit the water. Diplomacy is suspended.');});canvas.addEventListener('mousemove',e=>{let r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*W/r.width,y=(e.clientY-r.top)*H/r.height;hover=ducks.reduce((best,d)=>!best||Math.hypot(d.x-x,d.y-y)<Math.hypot(best.x-x,best.y-y)?d:best,null);if(hover&&Math.hypot(hover.x-x,hover.y-y)<42)$('duckCard').innerHTML=`<h2>${hover.name}</h2><p><strong>${hover.state}</strong> · hunger ${Math.round(hover.hunger*100)}%<br>${Object.keys(hover.friends).length?'Keeping a mental list of friends.':'Still making introductions.'}</p>`;else {$('duckCard').innerHTML='<h2>Meet the ducks</h2><p>Hover a duck to see what is on its mind.</p>';hover=null}});
  $('feed').onclick=()=>canvas.dispatchEvent(new MouseEvent('click',{clientX:canvas.getBoundingClientRect().left+W*.5*canvas.getBoundingClientRect().width/W,clientY:canvas.getBoundingClientRect().top+H*.5*canvas.getBoundingClientRect().height/H}));$('rain').onclick=()=>{rain=1;log('A warm rain begins. The pond changes its mind.');};$('lily').onclick=()=>{lilies.push({x:rand(90,W-90),y:rand(90,H-90),r:rand(17,33)});log('A new lily pad arrives. Someone will claim it soon.');};$('reset').onclick=reset;reset();setInterval(step,45);draw();
})();
