const $=id=>document.getElementById(id), ids=["symmetry","depth","reach","curl","irregularity","terminal","seed"];
const mulberry=a=>()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296};
function recipe(){let r={schema:"monad.beastDefinition.v0.1",family:"radial-hydra",symmetry:+$("symmetry").value,branch_depth:+$("depth").value,reach:+$("reach").value/100,curl:+$("curl").value/100,irregularity:+$("irregularity").value/100,terminal:$("terminal").value,seed:+$("seed").value};r.id=`hydra-${r.seed}-${r.symmetry}r${r.branch_depth}d`;return r}
function branchPoints(r,angle,level,rand){let pts=[],x=350,y=350,a=angle,len=245*r.reach;for(let i=0;i<22;i++){let t=i/21,j=(rand()-.5)*r.irregularity*.18;a+=r.curl*.018+j;x+=Math.cos(a)*len/22;y+=Math.sin(a)*len/22;pts.push([x,y])}return pts}
function terminalSvg(r,x,y,a){if(r.terminal==="eye")return `<circle cx="${x}" cy="${y}" r="10" fill="#061013" stroke="#efae4b" stroke-width="4"/><circle cx="${x}" cy="${y}" r="3" fill="#55ded1"/>`;if(r.terminal==="maw")return `<path d="M${x-12*Math.sin(a)},${y+12*Math.cos(a)} Q${x+16*Math.cos(a)},${y+16*Math.sin(a)} ${x+12*Math.sin(a)},${y-12*Math.cos(a)} Q${x-10*Math.cos(a)},${y-10*Math.sin(a)} ${x-12*Math.sin(a)},${y+12*Math.cos(a)}" fill="#ef7184" stroke="#efae4b"/>`;return `<path d="M${x},${y} l${28*Math.cos(a-.25)},${28*Math.sin(a-.25)} l${-20*Math.cos(a)},${-20*Math.sin(a)}Z" fill="#efae4b"/>`}
function schematic(r){let rand=mulberry(r.seed),paths="",ends="";for(let n=0;n<r.symmetry;n++){let base=n*Math.PI*2/r.symmetry+(rand()-.5)*r.irregularity*.22,p=branchPoints(r,base,0,rand),d=`M350 350 `+p.map(q=>`L${q[0].toFixed(1)} ${q[1].toFixed(1)}`).join(" ");paths+=`<path d="${d}" fill="none" stroke="#55ded1" stroke-width="8" stroke-linecap="round"/>`;let end=p.at(-1);ends+=terminalSvg(r,end[0],end[1],base);for(let level=1;level<=r.branch_depth;level++){let at=p[Math.max(5,21-level*5)];for(let s of[-1,1]){let a=base+s*(.38+.12*level),l=42+30*(r.branch_depth-level),x=at[0]+Math.cos(a)*l,y=at[1]+Math.sin(a)*l;paths+=`<path d="M${at[0]} ${at[1]} Q${(at[0]+x)/2+12*s} ${(at[1]+y)/2} ${x} ${y}" fill="none" stroke="#7aa9a3" stroke-width="${5-level}" stroke-linecap="round"/>`}}} $("schematic").innerHTML=`<circle cx="350" cy="350" r="70" fill="#102c2d" stroke="#efae4b" stroke-width="5"/><circle cx="350" cy="350" r="38" fill="#071719" stroke="#55ded1" stroke-dasharray="4 5"/>${paths}${ends}`}
function art(r){let c=$("concept"),x=c.getContext("2d"),rand=mulberry(r.seed+991);x.clearRect(0,0,900,900);let g=x.createRadialGradient(450,420,20,450,450,600);g.addColorStop(0,"#214e4c");g.addColorStop(1,"#03070a");x.fillStyle=g;x.fillRect(0,0,900,900);x.save();x.translate(450,450);for(let n=0;n<r.symmetry;n++){let a=n*Math.PI*2/r.symmetry+(rand()-.5)*r.irregularity*.3;x.beginPath();x.moveTo(0,0);let px=0,py=0;for(let i=1;i<=35;i++){a+=r.curl*.012+(rand()-.5)*r.irregularity*.04;px+=Math.cos(a)*310*r.reach/35;py+=Math.sin(a)*310*r.reach/35;x.lineTo(px,py)}x.strokeStyle=`hsl(${168+(rand()-.5)*22} 48% ${38+(rand()-.5)*10}%)`;x.lineWidth=30;x.lineCap="round";x.shadowBlur=18;x.shadowColor="#3bdfcc55";x.stroke();x.shadowBlur=0;x.fillStyle=r.terminal==="maw"?"#e76b80":r.terminal==="spike"?"#efae4b":"#55ded1";x.beginPath();x.arc(px,py,r.terminal==="eye"?12:8,0,Math.PI*2);x.fill()}x.fillStyle="#153b3c";x.strokeStyle="#efae4b";x.lineWidth=8;x.beginPath();x.arc(0,0,95,0,Math.PI*2);x.fill();x.stroke();for(let i=0;i<7;i++){let a=i*Math.PI*2/7;x.fillStyle=i%2?"#55ded1":"#efae4b";x.beginPath();x.arc(Math.cos(a)*52,Math.sin(a)*52,8,0,Math.PI*2);x.fill()}x.restore();x.fillStyle="#d9eee8aa";x.font="18px monospace";x.fillText(r.id,24,870)}
function update(){let r=recipe();ids.slice(0,5).forEach(id=>$(id+"Out").textContent=$(id).value);$("definition").textContent=JSON.stringify(r,null,2);schematic(r);art(r);let q=new URLSearchParams();ids.forEach(id=>q.set(id,$(id).value));history.replaceState(null,"",`${location.pathname}?${q}`)}
function load(){let q=new URLSearchParams(location.search);ids.forEach(id=>{if(q.has(id))$(id).value=q.get(id)})}
ids.forEach(id=>$(id).addEventListener("input",update));$("render").onclick=()=>art(recipe());$("newSeed").onclick=()=>{$("seed").value=Math.floor(Math.random()*999999)+1;update()};$("mutate").onclick=()=>{let r=mulberry(recipe().seed+Date.now());$("seed").value=Math.floor(r()*999999)+1;$("irregularity").value=Math.min(60,+$("irregularity").value+Math.round((r()-.5)*12));update()};
function download(name,blob){let a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$("saveRecipe").onclick=()=>download(recipe().id+".json",new Blob([JSON.stringify(recipe(),null,2)],{type:"application/json"}));$("saveImage").onclick=()=>$("concept").toBlob(b=>download(recipe().id+".png",b));$("copyLink").onclick=async()=>{await navigator.clipboard.writeText(location.href);$("status").textContent="Permalink copied."};load();update();
