#!/usr/bin/env python3
"""HTTP trigger for toys/asset-viewer/'s upload button. Routes on what
you upload:

- An image -> runs real inference via the replicate backend
  (tencent/hunyuan-3d-3.1, verified 2026-07-12 to produce properly
  UV-textured output). This is real, per-second-billed money against
  whatever account REPLICATE_API_TOKEN belongs to -- every upload spends
  it. Requires REPLICATE_API_TOKEN set in this process's environment.
- A .glb -> just validated and cataloged, same as always (e.g. something
  generated by hand through a ZeroGPU Space's web UI, since those reject
  gradio_client/API-originated calls -- see hf_spaces.py's docstring for
  that investigation).

Loopback-only by default (127.0.0.1), same posture as fleetcore-serve's
own DEFAULT_BIND_HOST -- but the stakes here are higher than that
pattern usually implies: with --bind-all, anything on the LAN can
trigger real charges against your Replicate account with zero
confirmation step, not just write into the public web/ tree. Don't pass
--bind-all without meaning it.

Usage:
    python3 serve.py [--port 8501] [--bind-all]
"""
import argparse
import json
import os
import re
import time
import traceback
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

from image_to_asset import run_pipeline, REPO_ROOT

INPUT_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "input")
DEFAULT_PORT = 8501
MAX_UPLOAD_BYTES = 30 * 1024 * 1024  # generous for a textured GLB (2048px textures included), not unbounded


def safe_output_name(raw_name: str) -> str:
    """Client-supplied name is a display convenience only -- never trusted
    as a path. Strip to a safe basename before it ever touches the
    filesystem, same spirit as werkzeug's secure_filename but with no new
    dependency for one function."""
    stem = os.path.splitext(os.path.basename(raw_name or "asset"))[0]
    stem = re.sub(r"[^a-zA-Z0-9_-]+", "-", stem).strip("-") or "asset"
    return f"{stem[:60]}.glb"


def parse_multipart(body: bytes, boundary: bytes):
    """Minimal single-file multipart/form-data parser -- this endpoint only
    ever needs one file field, so a full multipart library is more
    dependency than the job needs. Returns (filename, file_bytes) or
    (None, None) if no file part is found."""
    parts = body.split(b"--" + boundary)
    for part in parts:
        if b"Content-Disposition" not in part:
            continue
        header_end = part.find(b"\r\n\r\n")
        if header_end == -1:
            continue
        headers = part[:header_end].decode("utf-8", errors="replace")
        match = re.search(r'filename="([^"]*)"', headers)
        if not match or not match.group(1):
            continue
        content = part[header_end + 4:]
        if content.endswith(b"\r\n"):
            content = content[:-2]
        return match.group(1), content
    return None, None


class Handler(BaseHTTPRequestHandler):
    def _send_json(self, status: int, payload: dict) -> None:
        body = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        # Loopback-bound by default (see module docstring) is the real
        # access control here; CORS-open matches fleetcore-serve's own
        # snapshot endpoint rather than inventing a second policy.
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(body)

    def do_OPTIONS(self):
        self.send_response(204)
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Access-Control-Allow-Methods", "POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type, X-Output-Name")
        self.end_headers()

    def do_POST(self):
        if self.path != "/generate":
            self._send_json(404, {"ok": False, "error": "not found"})
            return

        content_type = self.headers.get("Content-Type", "")
        boundary_match = re.search(r"boundary=([^;]+)", content_type)
        length = int(self.headers.get("Content-Length", 0))
        if not boundary_match or length <= 0:
            self._send_json(400, {"ok": False, "error": "expected multipart/form-data with a file"})
            return
        if length > MAX_UPLOAD_BYTES:
            self._send_json(413, {"ok": False, "error": f"upload too large (max {MAX_UPLOAD_BYTES // (1024 * 1024)} MB)"})
            return

        body = self.rfile.read(length)
        boundary = boundary_match.group(1).strip('"').encode("utf-8")
        filename, file_bytes = parse_multipart(body, boundary)
        if not filename or not file_bytes:
            self._send_json(400, {"ok": False, "error": "no file found in upload"})
            return

        is_glb = filename.lower().endswith(".glb")
        is_image = filename.lower().endswith((".png", ".jpg", ".jpeg", ".webp"))
        if not is_glb and not is_image:
            self._send_json(400, {"ok": False, "error": f"unrecognized file type '{filename}' -- expected an image (to generate) or a .glb (to catalog)"})
            return
        backend = "manual" if is_glb else "replicate"
        if backend == "replicate" and not os.environ.get("REPLICATE_API_TOKEN"):
            self._send_json(400, {"ok": False, "error": "REPLICATE_API_TOKEN isn't set in this server's environment -- image uploads need it to run real (paid) inference. Restart serve.py with it exported, or upload a .glb instead to just catalog."})
            return

        output_name = safe_output_name(self.headers.get("X-Output-Name") or filename)
        os.makedirs(INPUT_DIR, exist_ok=True)
        ext = os.path.splitext(filename)[1] or (".glb" if is_glb else ".png")
        input_path = os.path.join(INPUT_DIR, f"upload-{int(time.time())}-{os.path.splitext(output_name)[0]}{ext}")
        with open(input_path, "wb") as f:
            f.write(file_bytes)

        print(f"[serve] received {filename} ({len(file_bytes)} bytes) -> {backend} as {output_name}")
        try:
            entry = run_pipeline(input_path, output_name, backend=backend, log=lambda msg: print(f"[serve] {msg}"))
            self._send_json(200, {"ok": True, "entry": entry})
        except SystemExit as exc:
            self._send_json(400, {"ok": False, "error": str(exc)})
        except Exception as exc:  # noqa: BLE001 -- this is a job-status boundary, report and move on
            traceback.print_exc()
            self._send_json(502, {"ok": False, "error": str(exc)})

    def log_message(self, fmt, *args):
        print(f"[serve] {self.address_string()} - {fmt % args}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--port", type=int, default=DEFAULT_PORT)
    parser.add_argument("--bind-all", action="store_true", help="bind 0.0.0.0 instead of loopback-only")
    args = parser.parse_args()

    host = "0.0.0.0" if args.bind_all else "127.0.0.1"
    server = ThreadingHTTPServer((host, args.port), Handler)
    print(f"img2asset trigger server on {host}:{args.port} (repo root: {REPO_ROOT})")
    if args.bind_all:
        print("WARNING: --bind-all means anything on the LAN can trigger real, billed Replicate generations (if REPLICATE_API_TOKEN is set) or upload files into the publicly-served web/ tree.")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    import sys
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    main()
