const API="/libfive-api",$=s=>document.querySelector(s),statusEl=$("#status"),message=$("#message"),catalog=$("#catalog"),canvas=$("#canvas"),ctx=canvas.getContext("2d"),drop=$("#dropZone"),fileInput=$("#sourceFile"),build=$("#generate");let recipe=null,apiReady=false,vertices=[],rx=-.45,ry=.65,zoom=1,drag=null;
function step(name,state){let el=document.querySelector(`[data-step="${name}"]`);el.className=state||""}function resetSteps(){document.querySelectorAll(".progress li").forEach(x=>x.className="")}
function validate(value){if(!value||typeof value!=="object")throw Error("Recipe must be a JSON object.");let allowed={sphere:["shape","name","radius"],box:["shape","name","size"],torus:["shape","name","radius","minor"]};if(!allowed[value.shape])throw Error("shape must be sphere, box, or torus.");if(Object.keys(value).some(k=>!allowed[value.shape].includes(k)))throw Error("Recipe contains unsupported fields.");if(!/^[a-z0-9][a-z0-9-]{0,47}$/.test(value.name||""))throw Error("name must use lowercase letters, numbers, and hyphens.");let range=(key,min,max)=>{if(typeof value[key]!=="number"||value[key]<min||value[key]>max)throw Error(`${key} must be ${min}–${max}.`)};if(value.shape==="box")range("size",1,200);else range("radius",1,100);if(value.shape==="torus"){range("minor",.5,50);if(value.minor>=value.radius)throw Error("minor must be smaller than radius.")}return value}
async function loadSource(file){resetSteps();let readDone=false;step("read","active");message.textContent="Reading source…";try{if(!file.name.toLowerCase().endsWith(".json"))throw Error("Choose a .json recipe file.");if(file.size>4096)throw Error("Recipe exceeds 4 KB.");let text=await file.text();readDone=true;step("read","done");step("validate","active");recipe=validate(JSON.parse(text));step("validate","done");$("#sourceSummary").textContent=`${file.name} · ${recipe.shape} · output ${recipe.name}.stl`;message.textContent="Recipe ready to build.";build.disabled=!apiReady}catch(error){recipe=null;step("read",readDone?"done":"failed");step("validate","failed");$("#sourceSummary").textContent="Source rejected.";message.textContent=error.message;build.disabled=true}}
drop.onclick=()=>fileInput.click();drop.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();fileInput.click()}};fileInput.onchange=()=>fileInput.files[0]&&loadSource(fileInput.files[0]);["dragenter","dragover"].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.add("is-over")}));["dragleave","drop"].forEach(n=>drop.addEventListener(n,e=>{e.preventDefault();drop.classList.remove("is-over")}));drop.addEventListener("drop",e=>e.dataTransfer.files[0]&&loadSource(e.dataTransfer.files[0]));
function render(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.strokeStyle="#78d6ca";ctx.lineWidth=.7;if(!vertices.length){ctx.fillStyle="#668086";ctx.font="18px system-ui";ctx.fillText("Output viewer",canvas.width/2-55,canvas.height/2);return}const cy=Math.cos(ry),sy=Math.sin(ry),cx=Math.cos(rx),sx=Math.sin(rx),pts=vertices.map(v=>{let x=v[0]*cy+v[2]*sy,z=-v[0]*sy+v[2]*cy,y=v[1]*cx-z*sx;return[x,y]});let max=Math.max(...pts.flatMap(p=>p.map(Math.abs)))||1,s=Math.min(canvas.width,canvas.height)*.38/max*zoom;for(let i=0;i<pts.length;i+=3){ctx.beginPath();pts.slice(i,i+3).forEach((p,j)=>j?ctx.lineTo(canvas.width/2+p[0]*s,canvas.height/2-p[1]*s):ctx.moveTo(canvas.width/2+p[0]*s,canvas.height/2-p[1]*s));ctx.closePath();ctx.stroke()}}
function parseSTL(buffer){let view=new DataView(buffer),out=[];if(buffer.byteLength>=84){let count=view.getUint32(80,true);if(84+count*50===buffer.byteLength){for(let i=0;i<count;i++)for(let v=0;v<3;v++){let b=84+i*50+12+v*12;out.push([view.getFloat32(b,true),view.getFloat32(b+4,true),view.getFloat32(b+8,true)])}return out}}let text=new TextDecoder().decode(buffer),re=/vertex\s+([\-\d.e+]+)\s+([\-\d.e+]+)\s+([\-\d.e+]+)/gi,m;while((m=re.exec(text)))out.push([+m[1],+m[2],+m[3]]);return out}
async function preview(model){let url="../../"+model.stl_path.replace(/^web\//,""),response=await fetch(url);vertices=parseSTL(await response.arrayBuffer());$("#previewTitle").textContent=model.name;Object.assign($("#download"),{hidden:false,href:url,download:model.name+".stl"});rx=-.45;ry=.65;zoom=1;render()}
function cards(models){$("#count").textContent=`${models.length} model${models.length===1?"":"s"}`;catalog.innerHTML=models.length?models.slice().reverse().map((m,i)=>`<article class="model" tabindex="0" data-i="${models.length-1-i}"><strong>${m.name}</strong><small class="tag">${m.primitive}</small><small>${m.sha256.slice(0,16)}…</small></article>`).join(""):"<p>No generated models yet.</p>";catalog.querySelectorAll(".model").forEach(el=>{let open=()=>preview(models[+el.dataset.i]);el.onclick=open;el.onkeydown=e=>e.key==="Enter"&&open()})}
async function refresh(){try{let r=await fetch(API+"/status",{cache:"no-store"}),d=await r.json();apiReady=Boolean(d.installed);statusEl.textContent=apiReady?"Exporter Ready":"Exporter Offline";statusEl.classList.toggle("ready",apiReady);build.disabled=!apiReady||!recipe;cards(d.models||[])}catch{apiReady=false;statusEl.textContent="API Offline";build.disabled=true;try{cards((await fetch("../../assets/libfive/manifest.json").then(r=>r.json())).models||[])}catch{cards([])}}}
build.onclick=async()=>{if(!recipe)return;step("generate","active");message.textContent="Generating mesh…";build.disabled=true;try{let r=await fetch(API+"/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(recipe)}),d=await r.json();if(!r.ok)throw Error(d.error||`status ${r.status}`);step("generate","done");step("load","active");await refresh();await preview(d);step("load","done");message.textContent=`Built and loaded ${d.name}.stl.`}catch(error){step("generate","failed");message.textContent=`Build failed: ${error.message}`}finally{build.disabled=!apiReady||!recipe}};
canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drag)return;ry+=(e.clientX-drag[0])*.01;rx+=(e.clientY-drag[1])*.01;drag=[e.clientX,e.clientY];render()};canvas.onpointerup=()=>drag=null;canvas.onwheel=e=>{e.preventDefault();zoom=Math.max(.3,Math.min(4,zoom*(e.deltaY>0?.9:1.1)));render()};render();refresh();
