const API="/libfive-api";const $=s=>document.querySelector(s);const form=$("#form"),shape=$("#shape"),statusEl=$("#status"),message=$("#message"),catalog=$("#catalog"),canvas=$("#canvas"),ctx=canvas.getContext("2d");let vertices=[],rx=-.45,ry=.65,zoom=1,drag=null;
function dimensions(){document.querySelectorAll("[data-for]").forEach(x=>x.hidden=!x.dataset.for.split(" ").includes(shape.value))}shape.addEventListener("change",dimensions);dimensions();
function render(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.strokeStyle="#78d6ca";ctx.lineWidth=.7;if(!vertices.length){ctx.fillStyle="#668086";ctx.font="18px system-ui";ctx.fillText("No mesh loaded",canvas.width/2-65,canvas.height/2);return}const cy=Math.cos(ry),sy=Math.sin(ry),cx=Math.cos(rx),sx=Math.sin(rx);const pts=vertices.map(v=>{let x=v[0]*cy+v[2]*sy,z=-v[0]*sy+v[2]*cy,y=v[1]*cx-z*sx;z=v[1]*sx+z*cx;return[x,y,z]});let max=Math.max(...pts.flatMap(p=>[Math.abs(p[0]),Math.abs(p[1])]))||1,scale=Math.min(canvas.width,canvas.height)*.38/max*zoom;for(let i=0;i<pts.length;i+=3){ctx.beginPath();for(let j=0;j<3;j++){let p=pts[i+j],x=canvas.width/2+p[0]*scale,y=canvas.height/2-p[1]*scale;j?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath();ctx.stroke()}}
function parseSTL(buffer){const view=new DataView(buffer);let out=[];if(buffer.byteLength>=84){let count=view.getUint32(80,true);if(84+count*50===buffer.byteLength){for(let i=0;i<count;i++){let base=84+i*50+12;for(let v=0;v<3;v++)out.push([view.getFloat32(base+v*12,true),view.getFloat32(base+v*12+4,true),view.getFloat32(base+v*12+8,true)])}return out}}const text=new TextDecoder().decode(buffer),re=/vertex\s+([\-\d.e+]+)\s+([\-\d.e+]+)\s+([\-\d.e+]+)/gi;let m;while((m=re.exec(text)))out.push([+m[1],+m[2],+m[3]]);return out}
async function preview(model){const url="../../"+model.stl_path.replace(/^web\//,"");let response=await fetch(url);vertices=parseSTL(await response.arrayBuffer());$("#previewTitle").textContent=model.name;$("#download").hidden=false;$("#download").href=url;$("#download").download=model.name+".stl";rx=-.45;ry=.65;zoom=1;render()}
function cards(models){$("#count").textContent=`${models.length} model${models.length===1?"":"s"}`;catalog.innerHTML=models.length?models.slice().reverse().map((m,i)=>`<article class="model" tabindex="0" data-i="${models.length-1-i}"><strong>${m.name}</strong><small class="tag">${m.primitive}</small><small>${m.sha256.slice(0,16)}…</small><small>${new Date(m.created_at).toLocaleString()}</small></article>`).join(""):"<p>No generated models yet.</p>";catalog.querySelectorAll(".model").forEach(el=>{let open=()=>preview(models[+el.dataset.i]);el.onclick=open;el.onkeydown=e=>{if(e.key==="Enter")open()}})}
async function refresh(){try{let r=await fetch(API+"/status",{cache:"no-store"}),d=await r.json();statusEl.textContent=d.installed?"Exporter Ready":"Exporter Offline";statusEl.classList.toggle("ready",d.installed);$("#generate").disabled=!d.installed;cards(d.models||[])}catch(e){statusEl.textContent="API Offline";$("#generate").disabled=true;try{let d=await fetch("../../assets/libfive/manifest.json").then(r=>r.json());cards(d.models||[])}catch{cards([])}}}
form.addEventListener("submit",async e=>{e.preventDefault();message.textContent="Generating mesh…";$("#generate").disabled=true;let payload={shape:shape.value,name:$("#name").value,radius:+$("#radius").value,size:+$("#size").value,minor:+$("#minor").value};try{let r=await fetch(API+"/generate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw Error(d.error||`status ${r.status}`);message.textContent=`Generated ${d.name}.`;await refresh();await preview(d)}catch(error){message.textContent=`Generation failed: ${error.message}`}finally{if(statusEl.classList.contains("ready"))$("#generate").disabled=false}});
canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drag)return;ry+=(e.clientX-drag[0])*.01;rx+=(e.clientY-drag[1])*.01;drag=[e.clientX,e.clientY];render()};canvas.onpointerup=()=>drag=null;canvas.onwheel=e=>{e.preventDefault();zoom=Math.max(.3,Math.min(4,zoom*(e.deltaY>0?.9:1.1)));render()};render();refresh();
